#ifndef _CONFIG
#define _CONFIG 1

/* EEPROM */
#define EEPROM_SIZE 12
#define CONFIG_SLOT_LOADCELL_OFFSET 0
#define CONFIG_SLOT_LOADCELL_READ_SAMPLES 1

/* HX711 Amplifier for Load Cell*/
const uint8_t LOADCELL_DOUT_PIN = D6;
const uint8_t LOADCELL_SCK_PIN = D7;

#define LOADCELL_CALIBRATION_OFFSET 54857
//#define LOADCELL_CALIBRATION_VALUE 333914
#define LOADCELL_CALIBRATION_REFERENCE 253.0

//#define LOADCELL_CALIBRATION_RATIO ((LOADCELL_CALIBRATION_VALUE) - (LOADCELL_CALIBRATION_OFFSET) / (LOADCELL_CALIBRATION_REFERENCE))
#define LOADCELL_CALIBRATION_RATIO 1102.63
#define LOADCELL_READ_SAMPLES 15

/* NFC Module */
const uint8_t PN532_IRQ = D2;
const uint8_t PN532_RESET = D3;

const uint16_t PN532_READ_TIMEOUT = 50U;

#endif /* _CONFIG */